-- ============================================================
-- inventory_upgrade.sql
-- Run AFTER generating BCrypt hashes with PasswordHashHelper.java
-- ============================================================

-- Step 1: Widen the password column to fit BCrypt hashes (60 chars)
ALTER TABLE userinfo MODIFY COLUMN password VARCHAR(255) NOT NULL;

-- Step 2: Update existing user passwords with BCrypt hashes
--         PASTE the hashes generated by PasswordHashHelper.java below
--         Replace the placeholder text between the single quotes

UPDATE userinfo SET password = '$2a$10$5z0xgXpU/yN7FPZXALNMzOgJ.E9h7w1Ky6K/DLJkqiu2fsn9pXIZi'
WHERE username = 'admin';

UPDATE userinfo SET password = '$2a$10$3KwLUTNiGnueyUopzQaRRugpZxICN3cMobbetBKdEfKwtp9JRH.F.'
WHERE username = 'admin1';

-- ============================================================
-- EXAMPLE of what it should look like after pasting:
-- UPDATE userinfo SET password = '$2a$10$xKz...full60charHash'
-- WHERE username = 'admin';
-- ============================================================

-- Step 3: Run this so you no longer have issues when trying to connect to the database like me

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION;
FLUSH PRIVILEGES;